import "./globals.css";
import styles from "./page.module.css";
import { Inter } from "next/font/google";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import FetchData from "./components/Fetchdata";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const Footerinfo = await FetchData("footer");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer data={Footerinfo} />
      </body>
    </html>
  );
}
